# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一数一世界
email: 524052035@qq.com
description: > # this means to ignore newlines until "baseurl:"
  专注数学，机器学习和数据挖掘应用
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bourneli.github.io" # the base hostname & protocol for your site
twitter_username: bourneli1
github_username:  bourneli
linkedin_username: bourneli
stackoverflow_username: bourneli


# Build settings
markdown: kramdown
